In [39]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [4]:
df = pd.DataFrame({
    'company': ['google','google','google','google','google','google','google'],
    'job':['sales executive','sales executive', 'business manager','business manager', 'computer Programmer', 'data scientist', 'software engineer'],
    'degree': ['bachelors','masters','bachelors', 'masters','bachelors','masters', 'bachelors']
})
df.to_csv('salaries.csv', index=False)

In [6]:
df = pd.read_csv('salaries.csv')
df.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer Programmer  bachelors

In [11]:
import numpy as np
series = pd.Series(np.random.randint(0,2,len(df['company'])))

In [12]:
series

0     0
1     1
2     1
3     1
4     0
5     1
6     1
7     0
8     0
9     0
10    1
11    0
12    0
13    1
14    0
15    1
16    0
17    0
18    1
19    1
20    0
21    0
22    0
23    0
24    1
25    0
26    0
27    1
28    0
dtype: int32

In [26]:
df = pd.concat((df, series),axis=1)
df

      company                  job     degree  0
0      google      sales executive  bachelors  0
1      google      sales executive    masters  1
2      google     business manager  bachelors  1
3      google     business manager    masters  1
4      google  computer Programmer  bachelors  0
5      google       data scientist    masters  1
6      google    software engineer  bachelors  1
7    facebook    software engineer  bachelors  0
8    facebook    software engineer    masters  0
9    facebook  computer Programmer  bachelors  0
10   facebook       data scientist    masters  1
11   facebook       data scientist  bachelors  0
12  microsoft    software engineer  bachelors  0
13  microsoft    software engineer    masters  1
14  microsoft    software engineer  bachelors  0
15  microsoft  computer Programmer    masters  1
16  microsoft       data scientist  bachelors  0
17  microsoft       data scientist  bachelors  0
18        tcs    software engineer    masters  1
19        tcs    software engineer  bachelors  1
20        tcs    software engineer    masters  0
21        tcs  computer Programmer  bachelors  0
22        tcs       data scientist  bachelors  0
23        tcs      sales executive    masters  0
24   facebook      sales executive  bachelors  1
25  microsoft      sales executive    masters  0
26        tcs      sales executive  bachelors  0
27  microsoft      sales executive  bachelors  1
28     google      sales executive    masters  0

In [27]:
df.columns

Index(['company', 'job', 'degree', 0], dtype='object')

In [28]:
df.rename(columns={0:'salary_more_than_100k'},inplace=True)

In [30]:
df.to_csv('salaries.csv')

In [31]:
# let's start the work now

df.columns

Index(['company', 'job', 'degree', 'salary_more_than_100k'], dtype='object')

In [32]:
inputs = df.drop('salary_more_than_100k', axis='columns')
target = df['salary_more_than_100k']

In [34]:
le_company =LabelEncoder()
le_job= LabelEncoder()
le_degree=LabelEncoder()

In [35]:
# we can also add columns like this 

inputs['company_name'] =le_company.fit_transform(inputs['company'])
inputs['job_title'] =le_job.fit_transform(inputs['job'])
inputs['degree_level'] =le_degree.fit_transform(inputs['degree'])

In [37]:
inputs

,company,job,degree,company_name,job_title,degree_level
0,google,sales executive,bachelors,1,3,0
1,google,sales executive,masters,1,3,1
2,google,business manager,bachelors,1,0,0
3,google,business manager,masters,1,0,1
4,google,computer Programmer,bachelors,1,1,0
5,google,data scientist,masters,1,2,1
6,google,software engineer,bachelors,1,4,0
7,facebook,software engineer,bachelors,0,4,0
8,facebook,software engineer,masters,0,4,1
9,facebook,computer Programmer,bachelors,0,1,0
10,facebook,data scientist,masters,0,2,1
11,facebook,data scientist,bachelors,0,2,0
12,microsoft,software engineer,bachelors,2,4,0
13,microsoft,software engineer,masters,2,4,1
14,microsoft,software engineer,bachelors,2,4,0
15,microsoft,computer Programmer,masters,2,1,1
16,microsoft,data scientist,bachelors,2,2,0
17,microsoft,data scientist,bachelors,2,2,0
18,tcs,software engineer,masters,3,4,1
19,tcs,software engineer,bachelors,3,4,0
20,tcs,software engineer,masters,3,4,1
21,tcs,computer Programmer,bachelors,3,1,0
22,tcs,data scientist,bachelors,3,2,0
23,tcs,sales executive,masters,3,3,1
24,facebook,sales executive,bachelors,0,3,0
25,microsoft,sales executive,masters,2,3,1
26,tcs,sales executive,bachelors,3,3,0
27,microsoft,sales executive,bachelors,2,3,0
28,google,sales executive,masters,1,3,1

In [38]:
inputs_n = inputs.drop(['company','job','degree'], axis='columns')
inputs_n

    company_name  job_title  degree_level
0              1          3             0
1              1          3             1
2              1          0             0
3              1          0             1
4              1          1             0
5              1          2             1
6              1          4             0
7              0          4             0
8              0          4             1
9              0          1             0
10             0          2             1
11             0          2             0
12             2          4             0
13             2          4             1
14             2          4             0
15             2          1             1
16             2          2             0
17             2          2             0
18             3          4             1
19             3          4             0
20             3          4             1
21             3          1             0
22             3          2             0
23             3          3             1
24             0          3             0
25             2          3             1
26             3          3             0
27             2          3             0
28             1          3             1

In [40]:
model = DecisionTreeClassifier()

In [41]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [43]:
model.score(inputs_n, target)

0.9310344827586207

In [50]:
model.predict([[2,2,1]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])