In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [22]:
df = pd.read_csv('titanic.csv')
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [23]:
df = df[['Pclass','Sex','Age', 'Fare', 'Survived']]

In [24]:
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [25]:
target =df.Survived
inputs =df.drop('Survived',axis='columns')

In [26]:
dummies=pd.get_dummies(inputs.Sex)
dummies

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [27]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [28]:
inputs.drop('Sex', axis='columns', inplace=True)

In [29]:
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [30]:
inputs.isna().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [19]:
inputs.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [32]:
import math
inputs.Age = inputs.Age.fillna(math.floor(inputs.Age.mean()))
inputs.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    29.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [33]:
inputs.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [40]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [41]:
model = GaussianNB() #used when data distribution is normal

In [42]:
model.fit(X_train, y_train)

GaussianNB()

In [43]:
model.score(X_test,y_test) #varies bcs of taken different sample data each time of execution of train_test_split()

0.7649253731343284

In [45]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

In [46]:
y_test[:10]

471    0
261    1
847    0
155    0
354    0
246    0
237    1
876    0
789    0
257    1
Name: Survived, dtype: int64

In [47]:
model.predict_proba(X_test[:10])

array([[9.91351692e-01, 8.64830775e-03],
       [9.80552967e-01, 1.94470334e-02],
       [9.91227562e-01, 8.77243801e-03],
       [8.64161738e-01, 1.35838262e-01],
       [9.90741437e-01, 9.25856302e-03],
       [2.51441043e-02, 9.74855896e-01],
       [7.18319539e-03, 9.92816805e-01],
       [9.89383874e-01, 1.06161260e-02],
       [7.66192395e-01, 2.33807605e-01],
       [5.64286729e-04, 9.99435713e-01]])