In [5]:
import pandas as pd

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\pc\anaconda3\Lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in C:\Users\pc\anaconda3\Lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in C:\Users\pc\anaconda3\Lib\site-packages (from kagglehub) (23.0)
Requirement already satisfied: pyyaml in C:\Users\pc\anaconda3\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\pc\anaconda3\Lib\site-packages (from kagglehub) (2.31.0)
Requirement already satisfied: tqdm in C:\Users\pc\anaconda3\Lib\site-packages (from kagglehub) (4.65.0)
Requirement already satisfied: protobuf in C:\Users\pc\anaconda3\Lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (4.21.12)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\pc\anaconda3\Lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\pc\anaconda3\Lib\site-packages (from requests->kagglehub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\pc\anaconda3\Lib\site-packages (from requests->kagglehub) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\pc\anaconda3\Lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in C:\Users\pc\anaconda3\Lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("syedjaferk/indias-weather-data")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\pc\.cache\kagglehub\datasets\syedjaferk\indias-weather-data\versions\1

In [6]:
df = pd.read_csv("C:/Users/pc/.cache/kagglehub/datasets/syedjaferk/indias-weather-data/versions/1/weather_data.csv")

In [7]:
df.head()

,id,city_name,city_id,latitude,longitude,dt_txt,temp,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,main,description,clouds,wind_speed,wind_degree,region,state
0,103348,Amarawati,1263594,16.0,76.96,2020-01-29 08:30:00+05:30,23.45,23.45,23.45,1016,1016,971,59,Clouds,scattered clouds,44,2.83,312,West\n,Maharashtra
1,103349,Amarawati,1263594,16.0,76.96,2020-01-29 11:30:00+05:30,27.91,27.91,27.91,1015,1015,971,42,Clouds,few clouds,22,1.95,297,West\n,Maharashtra
2,103350,Amarawati,1263594,16.0,76.96,2020-01-29 14:30:00+05:30,31.14,31.14,31.14,1010,1010,967,34,Clear,clear sky,0,2.93,234,West\n,Maharashtra
3,103351,Amarawati,1263594,16.0,76.96,2020-01-29 17:30:00+05:30,30.94,30.94,30.94,1010,1010,966,32,Clear,clear sky,0,1.15,246,West\n,Maharashtra
4,103352,Amarawati,1263594,16.0,76.96,2020-01-29 20:30:00+05:30,26.14,26.14,26.14,1012,1012,968,41,Clear,clear sky,0,1.68,65,West\n,Maharashtra

In [ ]:
# to get max temp
df['temp_max'].max()

In [ ]:
df['main'].unique()

In [ ]:
# on which data it rained
df['dt_txt'][df['main']=='Rain']

In [ ]:
# average wind speed
df['wind_speed'].mean()

In [ ]:
# process of cleaning messy data is called data munging and data wrangling
df.isna().sum()

In [ ]:
(df['temp']!=df['temp_min']).sum()

In [9]:
df.size

112682440

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5634122 entries, 0 to 5634121
Data columns (total 20 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   city_name    object
 2   city_id      int64
 3   latitude     float64
 4   longitude    float64
 5   dt_txt       object
 6   temp         float64
 7   temp_min     float64
 8   temp_max     float64
 9   pressure     int64
 10  sea_level    int64
 11  grnd_level   int64
 12  humidity     int64
 13  main         object
 14  description  object
 15  clouds       int64
 16  wind_speed   float64
 17  wind_degree  int64
 18  region       object
 19  state        object
dtypes: float64(6), int64(8), object(6)
memory usage: 859.7+ MB

In [ ]:
df.describe()

In [ ]:
# create df from dictionary
weather_data = {
    'day':['01-01-2025','01-06-2025', '01-07-2025', '01-09-2025'],
    'temp': [32,43,22,23],
    'windspeed':[4,5,6,7],
    'event': ['rain', 'sunny', 'snow', 'rain']
}
df = pd.DataFrame(weather_data)
df

In [ ]:
df.shape

In [ ]:
rows, col = df.shape
rows

In [ ]:
col

In [ ]:
df[2:5]

In [ ]:
df.columns

In [ ]:
df['day']

In [ ]:
df.day

In [ ]:
type(df['day'])

In [ ]:
df.index

In [ ]:
df.set_index('day')

In [ ]:
df

In [ ]:
df.set_index('day', inplace=True)

In [ ]:
df

In [ ]:
df.loc['01-01-2025']

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

In [ ]:
# to read an excel file
df = pd.read_excel(r"C:\Users\pc\Desktop\job applications.xlsx", sheet_name='job applications')
df.head()

In [ ]:
# create df from list of tuple
weather_data = [
   ('01-01-2025',32, 4, 'rain'),
    ('01-06-2025',43,5,'sunny'),
    ('01-07-2025',22,6,'snow'),
    ('01-09-2025',23,7, 'cloud')
]
df = pd.DataFrame(weather_data, columns=['day','temp','windspeed','event'])
df

In [ ]:
# create df from list of dictionary
weather_data = [
   {'day':'01-01-2025',"temp": 32,'windspeed': 4, 'event':'rain'},
    {'day':'01-06-2025',"temp":43,'windspeed':5,'event':'sunny'},
    {'day':'01-07-2025',"temp":22,'windspeed':6,'event':'snow'},
    {'day':'01-09-2025',"temp":23,'windspeed':7, 'event':'cloud'}
]
df = pd.DataFrame(weather_data)
df

In [ ]:
# to skip first row 
df = pd.read_csv("", skiprows=1)
# or
df = pd.read_csv("", header=1, names=["","",""]) #names to name the columns

In [ ]:
df = pd.read_csv("", na_values=['not available', 'n.a.'])

In [ ]:
df = pd.read_csv("", na_values={'col':['not available', 'n.a.'],
                               'col': ['not available','n.a.',-1]}) #when the evenue cannot be negative

In [ ]:
# to save in new file
df.to_csv('file_name.csv',index=False) #to avoid default index

In [ ]:
def convert_cell(c):
    if c =='n.a.':
        return 'new value'
    return c
df = pd.read_excel("filename.xlsx", 'sheet1', converters={
    'coloumn name': convert_cell
})

In [ ]:
df.to_excel("filename.xlsx", sheet_name="name of sheet")

In [ ]:
# 2 dfs in one excel sheet with different sheets

with pd.ExcelWriter('excelfile.xlsx') as writer:
    df1.to_excel(writer, sheet_name="sheet_df1")
    df2.to_excel(writer, sheet_name="sheet_df2")

In [ ]:
# to make a date column as actual date type
df = pd.read_csv("csvfile", parse_dates=['day(colm name)'])

In [ ]:
# fillna with 0 for null values
df.fillna(0)

In [ ]:
newdf = df.fillna({
    'col name': 'value',
    'col name':'value'
})

In [ ]:
# imputation with forward fill and backward fill
newdf = df.fillna(method='ffill')
newdf = df.fillna(method='bfill')

In [ ]:
# filling acc to axis
newdf = df.fillna(method='ffill', axis='columns')

In [ ]:
# filling limit upto 1 means if 2 continuous rows are empty it will fill the first one only
new_df = df.fillna(method='ffill', limit=1)

In [ ]:
# not to get these inconsistency, we use interpolate
df1 = df.interpolate()

In [ ]:
# if we use method=time then it will consider the date and make adjustments acc to it
df1 = df.interpolate(method='time')

In [ ]:
# we can drop those rows which has all values as null
new=df.dropna(how='all')

In [ ]:
# contain the rows which has atleast 1 na values otherwise drop all

new = df.dropna(thresh=1)

In [ ]:
# insert the missing dates in date column
dt = pd.date_range("01-01-2017","01-12-2017")
idx = pd.DatetimeIndex(dt)
df=df.reindex(idx)
df

In [ ]:
import numpy as np
# replace method
df1 = df.replace(-9999, np.NaN)  #for multiple values we can use list in stead of one value
df1 = df.replace([-9999,-8888], np.NaN)
df1

In [ ]:
# replace values based on specific columns
df1 = df.replace({'temp':-9999,
                 'event':'0'}, np.NaN)

In [ ]:
# replace values based on specific values
df1 = df.replace({-9999: np.NaN,
                 'no event':'sunny'})
df1

In [ ]:
# replace unit from the numeric values
import regex
df1 = df.replace({'temp':'[A-Za-z]',
                  'windspeed':'[A-Za-z]'},"",regex=True)
df1

In [ ]:
df=pd.DataFrame({
    'score':['exceptional', 'average', 'good','poor','average','exceptional'],
    'student':['ryan','cheeku','parth','tiny','vish','kanak']
})
df

In [ ]:
df1=df.replace(['poor','average','good','exceptional'], [1,2,3,4])
df1

In [ ]:
# group by
score = df.groupby('score')
score

In [ ]:
for scale, df in score:
    print(scale)
    print(df)

In [ ]:
score.get_group('poor')

In [ ]:
score.max()

In [ ]:
score.min()

In [ ]:
score.describe()

In [ ]:
%matplotlib inline
score.plot()   #will work for numerical data

In [22]:
# pandas concat fn
india_weather = pd.DataFrame({
    'city': ['Delhi', 'Mumbai','Pune'],
    'temp': [23,23,32],
    'humidity':[56,76,87]
})

In [23]:
US_weather = pd.DataFrame({
    'city': ['Newyork', 'Manhattan','ocklahama'],
    'temp': [23,23,32],
    'humidity':[56,76,87]
})

In [24]:
wthr =pd.concat([india_weather, US_weather])
wthr

        city  temp  humidity
0      Delhi    23        56
1     Mumbai    23        76
2       Pune    32        87
0    Newyork    23        56
1  Manhattan    23        76
2  ocklahama    32        87

In [ ]:
wthr =pd.concat([india_weather, US_weather], ignore_index=True)
wthr

In [ ]:
wthr =pd.concat([india_weather, US_weather],keys=['India','US'])
wthr

In [ ]:
wthr.loc['US']

In [ ]:
in_windspd_weather = pd.DataFrame({
    'city': ['Delhi', 'Mumbai','Pune'],
    'windspeed': [23,23,32],
})

In [ ]:
df = pd.concat([india_weather,in_windspd_weather], axis=1)
df

In [16]:
india_weather = pd.DataFrame({
    'city': ['Delhi', 'Mumbai','Pune'],
    'temp': [23,23,32],
    'humidity':[56,76,87]
}, index=[0,1,2])

In [17]:
in_windspd_weather = pd.DataFrame({
    'city': [ 'Mumbai','Delhi'],
    'windspeed': [23,23],
}, index=[1,0])

In [ ]:
df =pd.concat([india_weather,in_windspd_weather],axis=1)

In [ ]:
ser = pd.Series(['humid','cloud','rain'], name='event')
ser

In [ ]:
df = pd.concat([df,ser], axis=1)
df

In [ ]:
df2 =pd.merge(india_weather,in_windspd_weather, on='city')
df2

In [ ]:
df3 =pd.merge(india_weather,in_windspd_weather, on='city', how='outer')
df3

In [ ]:
df3 =pd.merge(india_weather,in_windspd_weather, on='city', how='left')
df3

In [ ]:
df3 =pd.merge(india_weather,in_windspd_weather, on='city', how='right')
df3

In [ ]:
df3 =pd.merge(india_weather,in_windspd_weather, on='city', how='outer', indicator=True)
df3

In [ ]:
in_windspd_weather = pd.DataFrame({
    'city': [ 'Mumbai','Delhi'],
    'temp':[34,22],
    'windspeed': [23,23],
}, index=[1,0])

In [18]:
df3 =pd.merge(india_weather,in_windspd_weather, on='city', indicator=True)
df3

     city  temp  humidity  windspeed _merge
0   Delhi    23        56         23   both
1  Mumbai    23        76         23   both

In [19]:
# # pivot allows to reshape and transform dataframes
# df3.pivot(index='humidity',columns='city')

          temp        windspeed        _merge
city     Delhi Mumbai     Delhi Mumbai  Delhi Mumbai
humidity
56        23.0    NaN      23.0    NaN   both    NaN
76         NaN   23.0       NaN   23.0    NaN   both

In [25]:
india_weather = pd.DataFrame({
    'date':['01-01-2026','01-02-2026','01-03-2026'],
    'city': ['Delhi', 'Mumbai','Pune'],
    'temp': [23,23,32],
    'humidity':[56,76,87]
})

In [31]:
US_weather = pd.DataFrame({
    'date':['01-01-2026','01-02-2026','01-03-2026'],
    'city': ['Newyork', 'Manhattan','ocklahama'],
    'temp': [23,23,32],
    'humidity':[56,76,87]
})

In [32]:
df = pd.concat([india_weather,US_weather])

In [33]:
df

         date       city  temp  humidity
0  01-01-2026      Delhi    23        56
1  01-02-2026     Mumbai    23        76
2  01-03-2026       Pune    32        87
0  01-01-2026    Newyork    23        56
1  01-02-2026  Manhattan    23        76
2  01-03-2026  ocklahama    32        87

In [35]:
df.pivot(index='date', columns='city')

            temp                                          humidity            \
city       Delhi Manhattan Mumbai Newyork  Pune ocklahama    Delhi Manhattan
date
01-01-2026  23.0       NaN    NaN    23.0   NaN       NaN     56.0       NaN
01-02-2026   NaN      23.0   23.0     NaN   NaN       NaN      NaN      76.0
01-03-2026   NaN       NaN    NaN     NaN  32.0      32.0      NaN       NaN


city       Mumbai Newyork  Pune ocklahama
date
01-01-2026    NaN    56.0   NaN       NaN
01-02-2026   76.0     NaN   NaN       NaN
01-03-2026    NaN     NaN  87.0      87.0

In [34]:
df.pivot(index='date', columns='city', values='humidity')

city        Delhi  Manhattan  Mumbai  Newyork  Pune  ocklahama
date
01-01-2026   56.0        NaN     NaN     56.0   NaN        NaN
01-02-2026    NaN       76.0    76.0      NaN   NaN        NaN
01-03-2026    NaN        NaN     NaN      NaN  87.0       87.0

In [36]:
# pivot table summarize and aggregate the dataframe
us_df =pd.DataFrame({
    'date':['5/1/2026','5/1/2026','5/2/2026','5/2/2026'],
    'city':['new york','new york','new york','new york'],
    'temp':[65,61,70,75],
    'humidity':[56,54,60,62]
})

In [37]:
in_df =pd.DataFrame({
    'date':['5/1/2026','5/1/2026','5/2/2026','5/2/2026'],
    'city':['new delhi','new delhi','new delhi','new delhi'],
    'temp':[75,78,82,80],
    'humidity':[80,83,80,82]
})

In [38]:
df = pd.concat([us_df,in_df], ignore_index=True)
df

       date       city  temp  humidity
0  5/1/2026   new york    65        56
1  5/1/2026   new york    61        54
2  5/2/2026   new york    70        60
3  5/2/2026   new york    75        62
4  5/1/2026  new delhi    75        80
5  5/1/2026  new delhi    78        83
6  5/2/2026  new delhi    82        80
7  5/2/2026  new delhi    80        82

In [39]:
# pivot table allows to summarize and aggregate the dataframe
df.pivot_table(index='city', columns='date') #gives mean values

          humidity              temp
date      5/1/2026 5/2/2026 5/1/2026 5/2/2026
city
new delhi     81.5     81.0     76.5     81.0
new york      55.0     61.0     63.0     72.5

In [40]:
df.pivot_table(index='city',columns='date',aggfunc='sum')

          humidity              temp
date      5/1/2026 5/2/2026 5/1/2026 5/2/2026
city
new delhi      163      162      153      162
new york       110      122      126      145

In [41]:
df.pivot_table(index='city', columns='date', aggfunc='count')

          humidity              temp
date      5/1/2026 5/2/2026 5/1/2026 5/2/2026
city
new delhi        2        2        2        2
new york         2        2        2        2

In [42]:
df.pivot_table(index='city', columns='date', aggfunc='diff')

   humidity  temp
1        -2    -4
3         2     5
5         3     3
7         2    -2

In [44]:
df.pivot_table(index='city', columns='date', margins=True)

          humidity                      temp
date      5/1/2026 5/2/2026     All 5/1/2026 5/2/2026    All
city
new delhi    81.50     81.0  81.250    76.50    81.00  78.75
new york     55.00     61.0  58.000    63.00    72.50  67.75
All          68.25     71.0  69.625    69.75    76.75  73.25

In [45]:
in_df =pd.DataFrame({
    'date':['5/1/2026','5/1/2026','5/2/2026','5/2/2026'],
    'city':['new delhi','new delhi','new delhi','new delhi'],
    'temp':[75,78,82,80],
    'humidity':[80,83,80,82]
})

In [46]:
in_df

       date       city  temp  humidity
0  5/1/2026  new delhi    75        80
1  5/1/2026  new delhi    78        83
2  5/2/2026  new delhi    82        80
3  5/2/2026  new delhi    80        82

In [49]:
in_df['date'] =pd.to_datetime(in_df['date'])

In [52]:
type(in_df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [53]:
in_df.pivot_table(index=pd.Grouper(freq='M',key='date'), columns='city')

            humidity      temp
city       new delhi new delhi
date
2026-05-31     81.25     78.75

In [55]:
# pandas melt function - to transform and reshape data

df1=pd.melt(df, id_vars=['date'])

df1

        date  variable      value
0   5/1/2026      city   new york
1   5/1/2026      city   new york
2   5/2/2026      city   new york
3   5/2/2026      city   new york
4   5/1/2026      city  new delhi
5   5/1/2026      city  new delhi
6   5/2/2026      city  new delhi
7   5/2/2026      city  new delhi
8   5/1/2026      temp         65
9   5/1/2026      temp         61
10  5/2/2026      temp         70
11  5/2/2026      temp         75
12  5/1/2026      temp         75
13  5/1/2026      temp         78
14  5/2/2026      temp         82
15  5/2/2026      temp         80
16  5/1/2026  humidity         56
17  5/1/2026  humidity         54
18  5/2/2026  humidity         60
19  5/2/2026  humidity         62
20  5/1/2026  humidity         80
21  5/1/2026  humidity         83
22  5/2/2026  humidity         80
23  5/2/2026  humidity         82

In [56]:
df1[df1['value']=='new delhi']

       date variable      value
4  5/1/2026     city  new delhi
5  5/1/2026     city  new delhi
6  5/2/2026     city  new delhi
7  5/2/2026     city  new delhi

In [61]:
# reshaping technique - stacking and unstacking

df = pd.read_excel(r"C:\Users\pc\Desktop\job applications.xlsx", header=[0]) #header =0 bcs we have 1 heading line
df

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,NaN,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,NaN,"Python, React.Js, Django",Naukri,JD

In [66]:
df_stacked = df.stack(level=0)
df_stacked

0  S. No.                                                                              1
   Date                                                              2026-03-23 00:00:00
   Company Name                                           Comprinno Technologies Pvt.Ltd
   Post                                                                   Data Scientist
   Exp. Level                                                                    0-2 yrs
   Job Type (Remote/on site/Hybrid)                                              on site
   Interview type                                                        (Walk in drive)
   skills                               Python (Pandas, NumPy), ML basics + hands-on ...
   Platform                                                              company portal.
   JD link                                                                            JD
1  S. No.                                                                              2
   Date                                                              2026-03-24 00:00:00
   Company Name                                                            Infosys India
   Post                                                            Back Office Executive
   Job Type (Remote/on site/Hybrid)                                            part time
   Interview type                                                              got email
   skills                              proficiency in MS Excel, MS Word, and email co...
   Platform                                                              company portal.
   JD link                                                                            JD
2  S. No.                                                                              3
   Date                                                              2026-03-24 00:00:00
   Company Name                                                      Interview Kickstart
   Post                                                             Full Stack Developer
   Exp. Level                                                                1 - 3 Years
   Job Type (Remote/on site/Hybrid)                                            In office
   skills                                                       Python, React.Js, Django
   Platform                                                                       Naukri
   JD link                                                                            JD
dtype: object

In [67]:
df_stacked.unstack()

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23 00:00:00,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24 00:00:00,Infosys India,Back Office Executive,NaN,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24 00:00:00,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,NaN,"Python, React.Js, Django",Naukri,JD

In [69]:
# cross tab

in_df

        date       city  temp  humidity
0 2026-05-01  new delhi    75        80
1 2026-05-01  new delhi    78        83
2 2026-05-02  new delhi    82        80
3 2026-05-02  new delhi    80        82

In [72]:
pd.crosstab(in_df.city,in_df.date, margins=True, normalize=True)

date       2026-05-01 00:00:00  2026-05-02 00:00:00  All
city
new delhi                  0.5                  0.5  1.0
All                        0.5                  0.5  1.0

In [73]:
pd.crosstab(in_df.city,in_df.date, margins=True, normalize='index')

date       2026-05-01 00:00:00  2026-05-02 00:00:00
city
new delhi                  0.5                  0.5
All                        0.5                  0.5

In [77]:
import numpy as np
pd.crosstab(in_df.city,in_df.date, values=in_df.temp, aggfunc=np.average)

date       2026-05-01  2026-05-02
city
new delhi        76.5        81.0

In [ ]:
# read write data from sql

In [78]:
!pip install sqlalchemy
!pip install pymysql
import sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\pc\anaconda3\Lib\site-packages (2.0.21)
Requirement already satisfied: typing-extensions>=4.2.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sqlalchemy) (4.6.3)
Requirement already satisfied: greenlet!=0.4.17 in C:\Users\pc\anaconda3\Lib\site-packages (from sqlalchemy) (2.0.2)
Requirement already satisfied: pymysql in C:\Users\pc\anaconda3\Lib\site-packages (1.1.0)

In [ ]:
from sql
engine = sqlalchemy.create_engine('mysql+pymysql://root:Sana1234@localhost:3306/college_library')

In [86]:

with engine.connect() as conn:
    df = pd.read_sql_table('customer', conn)
df

   id Customer_Name Gender Issued_date Return_date  Book_id
0   1          Aman      M  2021-10-16  2021-11-16        2
1   2         Zaman      M  2021-10-18  2021-11-10        1
2   3        Anjali      F  2021-10-10  2021-11-05        1
3   4        Prachi      F  2021-10-09  2021-11-09        3
4   5          Ravi      M  2021-10-05  2021-11-05        5
5   6        Simran      F  2021-10-15  2021-11-15        4
6   7           Raj      M  2021-10-20  2021-11-20        3

In [91]:
from sqlalchemy import text
query = text('''select * from customer c''')
with engine.connect() as conn:
    df1= pd.read_sql_query(query, conn)
df1

   id Customer_Name Gender Issued_date Return_date  Book_id
0   1          Aman      M  2021-10-16  2021-11-16        2
1   2         Zaman      M  2021-10-18  2021-11-10        1
2   3        Anjali      F  2021-10-10  2021-11-05        1
3   4        Prachi      F  2021-10-09  2021-11-09        3
4   5          Ravi      M  2021-10-05  2021-11-05        5
5   6        Simran      F  2021-10-15  2021-11-15        4
6   7           Raj      M  2021-10-20  2021-11-20        3

In [92]:
# writing data from dataframe into sql
df = pd.read_excel(r"C:\Users\pc\Desktop\job applications.xlsx", header=[0]) #header =0 bcs we have 1 heading line
df

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,NaN,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,NaN,"Python, React.Js, Django",Naukri,JD

In [94]:
# create a new database in mysql
import sqlalchemy as s
from sqlalchemy import text

#1. connect to server
engine = s.create_engine('mysql+pymysql://root:Sana1234@localhost:3306/')

#2. name of new db
new_db = 'Job_application_db'
with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {new_db}"))
    print(f'{new_db} created successfully')

Job_application_db created successfully

In [95]:

# 1. Create a new engine connected to the specific database
engine_db = s.create_engine('mysql+pymysql://root:Sana1234@localhost:3306/Job_application_db')
df.to_sql(name="job_applications", con=engine_db, index=False, if_exists='replace') #if_exists can be 'append' etc.
print('Table created and data uploaded successfully')

Table created and data uploaded successfully

In [99]:
q = text('''select * from job_applications''')
with engine_db.connect() as conn:
    res = pd.read_sql_query(q,conn)
res

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [101]:
# let's change the column name
df=pd.read_sql_table('job_applications', engine_db.connect())
df

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [102]:
df.rename(columns={
    'Company Name':"Company"
}, inplace=True)

In [103]:
df

,S. No.,Date,Company,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [105]:
pd.read_sql('job_applications', engine_db.connect())

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [106]:
# read_sql use
pd.read_sql(q, engine_db.connect())

,S. No.,Date,Company Name,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
0,1,2026-03-23,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
1,2,2026-03-24,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2,3,2026-03-24,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [115]:
df.set_index('Date', inplace=True)

In [118]:
df.index

DatetimeIndex(['2026-03-23', '2026-03-24', '2026-03-24'], dtype='datetime64[ns]', name='Date', freq=None)

In [119]:
df['2026-03']  #by setting index of date we can check any date now

C:\Users\pc\AppData\Local\Temp\ipykernel_13560\1444000531.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  df['2026-03']

,S. No.,Company,Post,Exp. Level,Job Type (Remote/on site/Hybrid),Interview type,skills,Platform,JD link
Date,,,,,,,,,
2026-03-23,1,Comprinno Technologies Pvt.Ltd,Data Scientist,0-2 yrs,on site,(Walk in drive),"Python (Pandas, NumPy), ML basics + hands-on ...",company portal.,JD
2026-03-24,2,Infosys India,Back Office Executive,None,part time,got email,"proficiency in MS Excel, MS Word, and email co...",company portal.,JD
2026-03-24,3,Interview Kickstart,Full Stack Developer,1 - 3 Years,In office,None,"Python, React.Js, Django",Naukri,JD

In [ ]:
# monthly average price 
# df.specific_colum.resample('M'-> month).mean()
df.col.resample('M').mean()